<?php

namespace App\Services\Quiz\CaseSpecific;

use App\Enums\ReportTestCategory;

/**
 * A deterministic, hand-authored Case-Specific question template, keyed to one real
 * KBS rule_code. Never generated by an LLM. The template only fires when the KBS
 * RuleTrace for `ruleCode` actually fired (RuleTrace.fired === true) for the current
 * report's Analysis — see CaseSpecificQuestionBuilder. Question/option/explanation
 * wording is authored content (like the Phase 3B.2 General Question Bank); the
 * {label}/{value}/{unit} placeholders are filled from the real, per-report evidence
 * the fired rule returned, so every generated question is grounded in this specific
 * report's own verified/KBS data, never invented.
 */
final class CaseSpecificTemplate
{
    /**
     * @param  array<string, string>  $questionText  {en, ar} with optional {label}/{value}/{unit} placeholders
     * @param  array<string, array<string, string>>  $options  option_id => {en, ar}
     * @param  array<string, string>  $explanation  {en, ar} with optional {label}/{value}/{unit} placeholders
     */
    public function __construct(
        public readonly string $id,
        public readonly int $version,
        public readonly ReportTestCategory $category,
        public readonly string $ruleCode,
        public readonly string $conclusionCode,
        public readonly array $questionText,
        public readonly array $options,
        public readonly string $correctOptionId,
        public readonly array $explanation,
    ) {}

    /**
     * @param  list<array{source_id?: mixed, analyte_id?: string, label?: string, value?: mixed, unit?: ?string, status?: ?string}>  $evidence
     * @return array{
     *     question_text: array<string, string>,
     *     options: array<string, array<string, string>>,
     *     option_order: list<string>,
     *     correct_option_id: string,
     *     explanation: array<string, string>,
     *     case_specific_template_id: string,
     *     case_specific_template_version: int,
     *     evidence: array,
     *     rule_code: string,
     *     analyte_refs: list<string>,
     * }
     */
    public function buildDraft(array $evidence): array
    {
        $primary = $evidence[0] ?? [];
        $replacements = [
            '{label}' => (string) ($primary['label'] ?? ''),
            '{value}' => (string) ($primary['value'] ?? ''),
            '{unit}' => (string) ($primary['unit'] ?? ''),
        ];
        $fill = fn (array $text): array => array_map(
            static fn (string $s): string => strtr($s, $replacements),
            $text,
        );

        $optionOrder = array_keys($this->options);
        shuffle($optionOrder);

        return [
            'question_text' => $fill($this->questionText),
            'options' => $this->options,
            'option_order' => $optionOrder,
            'correct_option_id' => $this->correctOptionId,
            'explanation' => $fill($this->explanation),
            'case_specific_template_id' => $this->id,
            'case_specific_template_version' => $this->version,
            'evidence' => $evidence,
            'rule_code' => $this->ruleCode,
            'analyte_refs' => array_values(array_unique(array_filter(array_map(
                static fn (array $item): ?string => $item['analyte_id'] ?? null,
                $evidence,
            )))),
        ];
    }
}
